name: Deploy to GitHub Pages

on:
  push:
    branches:
      - lab7

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.2

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          flutter config --enable-web

      - name: Build Flutter web app
        run: |
          cd $GITHUB_WORKSPACE
          flutter pub get
          flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web